### ISSUE TITLE
errore con php7

### ISSUE THREAD

**Issue by camaran** [PorteAperteSulWeb/pasw2015#147]
con php7 ho errore 
Notice: Array to string conversion in /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php on line 894

Notice: Undefined property: Parsedown::$Array in /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php on line 894

Fatal error: Uncaught Error: Function name must be a string in /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php:894 Stack trace: #0 /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php(931): Parsedown->element(Array) #1 /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php(257): Parsedown->elements(Array) #2 /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php(48): Parsedown->lines(Array) #3 /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/src/GitHub_Updater/GitHub_API.php(128): Parsedown->text('Per la lista co...') #4 /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/src/GitHub_Updater/Theme.php(82): Fragen\GitHub_Updater\GitHub_API->get_remote_changes('CHANGELOG.md') #5 /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/src/GitHub_Up in /var/www/vhosts/webchat.domains/testchatme.ovh/wp-content/themes/pasw2015/github/vendor/Parsedown.php on line 894

**Comment by cghellere** [comment]
Da quanto vedo necessita attendere che GitHub aggiorni il suo plugin per l'update del tema.

PS php7 è stato rilasciato il 03 Dec 2015, penso che passerà un po' prima che venga considerato standard sui server web.

**Comment by rinorusso** [comment]
Anche se rilasciata credo sia raro utilizzare la versione 7 in ambienti di produzione. Ti consiglio di usare la versione 5 a meno che tu non sia in un ambiente di testing.

**Comment by milesimarco** [comment]
GitHub updater é stato realizzato da uno sviluppatore esterno alla piattaforma.  Il pacchetto incluso nel tema é fermo a una versione più vecchia perché le ultime hanno dato problemi. Occorre valutare qualche strada alternativa.  Una é quella di installarlo separatamente (verificando però che abbia la precedenza rispetto a quello incluso nel tema). Così facendo dovrebbe aggiornarsi in autonomia anche lui :) Il pacchetto é "afragen GitHub updater" Inviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [pasw2015] errore con php7 (#147)Da: Christian Ghellere A: PorteAperteSulWeb/pasw2015 CC: Da quanto vedo necessita attendere che GitHub aggiorni il suo plugin per l'update del tema.

PS php7 è stato rilasciato il 03 Dec 2015, penso che passerà un po' prima che venga considerato standard sui server web.

**Comment by milesimarco** [comment]
Ecco il liink:
https://github.com/afragen/github-updater

Prova a scaricare il plugin e installarlo separatamente.
