### ISSUE TITLE
Installazione del tema pasw2015-1.7 in WordPress 4.8.2

### ISSUE THREAD

**Issue by Ocantillo** [PorteAperteSulWeb/pasw2015#211]
Salve, 
sono alla fase iniziale di creazione del sito. Sto lavorando il locale con xmapp. Ho riscontrato alcuni problemi con l'installazione prima dei moduli in xml e poi del tema pasw2015-1.7 nella versione ultima di wordpress 4.8.2.
Il primo problema:
Wordpress Importer non carica tutto del file  xml: modello-sito.2014-11-07-corretto: quando vado a strutturare i menù superiore, principale ed inferiore non vengono caricati così come assegnati. Da quando ho letto la versione di Wordpress Importer non è stata testata con wordpress 4.8.2.
Secondo problema: 
wordpress mi segnala di cambiare il nome della cartella di pasw2015-1.7 in pasw2015, ma ho provato in tutti i modi ma non sono riuscito, ne direttamente ne effettuandoil cambio prima dell'installazione.

**Comment by cghellere** [comment]
Salve

il file di import ha qualche problema in quanto alcuni riferimenti non sono più attivi se non erro, vedi immagini.
Se lavori in locale ferma xmapp e poi vai nella cartella \wp-content\themes e prova a rinominare la cartella del tema in pasw2015, poi dovrai naturalmente riattivare il tema.
Attenzione alla versione del php, con la versione 7 ci sono degli errori.

**Comment by Ocantillo** [comment]
Ho provato con il cambio nome cartella dopo il blocco di xmapp e caricato nuovamente il tema. Mi ha dato questo errore:
Fatal error: Uncaught Error: Function name must be a string in C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\vendor\Parsedown.php:894 Stack trace: #0 C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\vendor\Parsedown.php(931): Parsedown->element(Array) #1 C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\vendor\Parsedown.php(257): Parsedown->elements(Array) #2 C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\vendor\Parsedown.php(48): Parsedown->lines(Array) #3 C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\src\GitHub_Updater\GitHub_API.php(128): Parsedown->text('Per la lista co...') #4 C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\src\GitHub_Updater\Theme.php(82): Fragen\GitHub_Updater\GitHub_API->get_remote_changes('CHANGELOG.md') #5 C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\src\GitHub_Updater\Base.php(125): Fragen\GitHub_Updater\Theme->__construct() #6 C:\xampp\htdocs\isaeclan in C:\xampp\htdocs\isaeclanum.gov.it\wp-content\themes\pasw2015\github\vendor\Parsedown.php on line 894

**Comment by sercola** [comment]
Salve seguo lo stesso errore do Ocantillo. Attendo Vostra soluzione

**Comment by cghellere** [comment]
E' un problema legato al modulo github e al php7, visto che si parla di test in locale mi pare che sia sufficiente commentare questa riga 
require (get_template_directory() . '/github/github-updater.php'); 
nel file functions.php prima di attivare il tema.

**Comment by Ocantillo** [comment]
Scusa, sono a  digiuno. Commentare cosa significa?

**Comment by cghellere** [comment]
Ciao 

per commentare in php o  //  prima della righa o /*  riga */
es. 
// require (get_template_directory() . '/github/github-updater.php');
o
/* require (get_template_directory() . '/github/github-updater.php'); +/

**Comment by Ocantillo** [comment]
Fatto, sembra tutto ok.
Adesso c'è il problema dell'import dei moduli per strutturare i menù.
Lavoro più complesso?

**Comment by renatadurighello** [comment]
Non è necessario importare moduli per strutturare i menù. Vai in Aspetto>Menù, ma imposrtando i modello dovresti trovare i menù già creati e resta solo da assegnargli la posizione

**Comment by renatadurighello** [comment]
Non è necessario importare moduli per strutturare i menù. Vai in Aspetto>Menù, ma imposrtando i modello dovresti trovare i menù già creati e resta solo da assegnargli la posizione

**Comment by Ocantillo** [comment]
Scusa, faccio ancora confusione tra i moduli e modelli.
Quando ho importato il modello, dopo aver caricato il modello mi segnala:
Fallita l'importazione di Media “puzzle”
Fallita l'importazione di Media “team”
Fallita l'importazione di Media “POF”
Fallita l'importazione di Media “organizzazione-strutture”
Fallita l'importazione di Media “calendario”
Fallita l'importazione di Media “segreteria”
Fallita l'importazione di Media “stretta-di-mano”
Fallita l'importazione di Media “iscrizioni”
Fallita l'importazione di Media “Libri_di_testo”
Fallita l'importazione di Media “modulistica”
Fallita l'importazione di Media “segreteria”
Fallita l'importazione di Media “alla-lavagna”
Fallita l'importazione di Media “Logo_UST”
Fallita l'importazione di Media “logo dirigente”
Fallita l'importazione di Media “logo-regolamento”
Fallita l'importazione di Media “logo-organigramma”
Fallita l'importazione di Media “sitemap_icon”
Fallita l'importazione di Media “icona-crediti”
Fallita l'importazione di Media “Logo_calendario”
Fallita l'importazione di Media “icona-pagamenti”
Fallita l'importazione di Media “immagine-progetti”
Fallita l'importazione di Media “logo-toolbox”
Fallita l'importazione di Media “orologio”
Fallita l'importazione di Media “Il file del tema (SchoolBell)”
Fallita l'importazione di Media “Il file di importazione del sito”.
Fa lo stesso ....

Poi in Aspetto > Personalizza > - non c'è Navigazione per Menù superiore, Menù principale e Menù inferiore, per cui non riesco a sistemare le barre di navigazione con la versione 4.8.2 di wordpress.


--

**Comment by renatadurighello** [comment]
![immagine](https://user-images.githubusercontent.com/9787217/31730081-17b24734-b431-11e7-9704-f28af8af9a30.png)

**Comment by Ocantillo** [comment]
Salve, sono stati assegnati in Gestione posizione di wordpress i vari menù e salvati. però non risultano in visualizzazione.

**Comment by Ocantillo** [comment]
Salve, scusate ma il problema che vi ho proposto "non risultano in visualizzazione i menù salvati" riguarda una mia errata azione di impostazione oppure è altro il problema ?
Grazie

**Comment by renatadurighello** [comment]
Scusa, credevo avessi risolto. Quindi i menu ci sono backend eppure non si vedono frontend? Puoi allegare uno screen?

**Comment by Ocantillo** [comment]
![menu](https://user-images.githubusercontent.com/32731678/32570903-fed6d5e0-c4c5-11e7-8e5b-de57c6aadc98.png)

**Comment by renatadurighello** [comment]
In effetti c'è qualcosa che  non va, ma non saprei da dove prendere. Controlla che le pagine ci siano e che i menù, oltre ad esistere, abbiano effettivamente le pagine che dovrebbero. Se non riesci a risolvere potrebbe valer la pena  cancellare tutto e ricominciare (se non hai inserito contenuti)
