### ISSUE TITLE
Problema installazione

### ISSUE THREAD

**Issue by maxilmanzoni** [PorteAperteSulWeb/pasw2015#234]
Buongiorno,
ho eseguito l'installazione pulita di Wordpress 5.2 con il Tema pasw2015 su Aruba Linux ma ho riscontrato il seguente errore:

Dettagli dell'errore
====================
Un errore di E_ERROR è stato causato nella linea 894 del file /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/vendor/Parsedown.php. Messaggio di errore: Uncaught Error: Function name must be a string in /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/vendor/Parsedown.php:894
Stack trace:
#0 /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/vendor/Parsedown.php(931): Parsedown->element(Array)
#1 /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/vendor/Parsedown.php(257): Parsedown->elements(Array)
#2 /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/vendor/Parsedown.php(48): Parsedown->lines(Array)
#3 /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/src/GitHub_Updater/GitHub_API.php(128): Parsedown->text('Per la lista co...')
#4 /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/src/GitHub_Updater/Theme.php(82): Fragen\GitHub_Updater\GitHub_API->get_remote_changes('CHANGELOG.md')
#5 /web/htdocs/www.figari.it/home/wordpress/wp-content/themes/pasw2015/github/src/GitHub_Updater/Base.php(125): Fragen\GitHub_Updater

Potreste gentilmente aiutarmi, grazie?

**Comment by maxilmanzoni** [comment]
Perfetto, sembra funzionare con l'installazione del plugin.
Ancora grazie, saluti.
