### ISSUE TITLE
WordPress - errore con iL tema PASW 2015

### ISSUE THREAD

**Issue by Raffaela77** [PorteAperteSulWeb/pasw2015#236]
Salve, ho ricevuto questo messaggio da wordPress appena ho cercato di entrare nel pannello amministratore  **senza riuscirci**:  
Ciao!
WordPress 5.2 ha una funzionalità integrata che rileva quando un plugin o un tema provoca un errore irreversibile sul tuo sito e ti avvisa con questa email automatica.
In questo caso, WordPress ha incontrato un errore con il tuo tema, PASW 2015.
Per prima cosa, vai al tuo sito web (http://www.icmoiano.edu.it/) e controlla se ci sono problemi visibili. Successivamente, vai nella pagina in cui è stato rilevato l'errore (http://www.icmoiano.edu.it/wp-admin/) e verifica se c'è qualche problema visibile.
Contatta il tuo host per richiedere assistenza per una investigazione più approfondita di questo problema.
Se il tuo sito appare danneggiato e non puoi accedere normalmente alla tua bacheca, WordPress ora ha una speciale "modalità di ripristino". Ciò ti consente di accedere in modo sicuro alla tua bacheca per controllare cosa non va...
**Dettagli dell'errore**
====================
Un errore di E_ERROR è stato causato nella linea 894 del file /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/vendor/Parsedown.php. Messaggio di errore: Uncaught Error: Function name must be a string in /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/vendor/Parsedown.php:894
Stack trace:
#0 /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/vendor/Parsedown.php(931): Parsedown->element(Array)
#1 /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/vendor/Parsedown.php(257): Parsedown->elements(Array)
#2 /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/vendor/Parsedown.php(48): Parsedown->lines(Array)
#3 /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/src/GitHub_Updater/GitHub_API.php(128): Parsedown->text('Per la lista co...')
#4 /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/src/GitHub_Updater/Theme.php(82): Fragen\GitHub_Updater\GitHub_API->get_remote_changes('CHANGELOG.md')
#5 /home2/icmoiacs/public_html/wp-content/themes/pasw2015/github/src/GitHub_Updater/Base.php(125): Fragen\GitHub_Updater\Theme->__construct()
#6 /home2/icmoiacs/public_html/wp-includes/class-wp-hook.php(286): Fr

Cliccando sul link sono riuscita ad entrare nel pannello grazie alla modalità "Recupero" di wordPress, ma ho problemi con l'home e con il sito che dal pannello amministratore mi risulta "Bianco"!!! Lunica cosa che ho fatto nei giorni scorsi è aver aggiornato la versione PHP 7
Come devo Procedere?
Vi ringrazio in anticipo

**Comment by kowalski215** [comment]
Disabiliterei temporaneamente l'updater di GitHub, che sembra non essere compatibile con PHP7. 
Accedi via FTP su wp-content/themes/pasw2015/
Apri il file functions.php
Commenta la quarta riga 
`require (get_template_directory() . '/github/github-updater.php');`
Aggiungendo /* */ all'inizio e alla fine
`/*require (get_template_directory() . '/github/github-updater.php');*/`
E' una soluzione temporanea che non consente poi l'aggiornamento del sito, ma per il passaggio al php7 (e direi in attesa del pasw2017) potrebbe andare..

**Comment by Mariaraffaela** [comment]
Grazie mille

**Comment by gioangio65** [comment]
Buon giorno.
Non riesco a risolvere il problema: Warning: Attempt to read property "option" on null in /web/htdocs/www.icsantomobono.edu.it/home/wp-content/themes/PorteAperteSulWeb-pasw2015-de2dad0/comments.php on line 18.
Cosa posso/devo fare?
Grazie. Giovanni
