### ISSUE TITLE
se utilizzo php 7.0 u superiore

### ISSUE THREAD

**Issue by aladinorazio** [PorteAperteSulWeb/pasw2015#238]
Inpostanto php da 5.6a 7.0 osuperiore, quandoeseguo il login come amministratore ecco cosa mi  restituisce:

Fatal error: Uncaught Error: Function name must be a string in /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/vendor/Parsedown.php:894 Stack trace: #0 /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/vendor/Parsedown.php(931): Parsedown->element(Array) #1 /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/vendor/Parsedown.php(257): Parsedown->elements(Array) #2 /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/vendor/Parsedown.php(48): Parsedown->lines(Array) #3 /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/src/GitHub_Updater/GitHub_API.php(128): Parsedown->text('Per la lista co...') #4 /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/src/GitHub_Updater/Theme.php(82): Fragen\GitHub_Updater\GitHub_API->get_remote_changes('CHANGELOG.md') #5 /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/src/GitHub_Updater/Base.php(125): Fragen\ in /web/htdocs/www.icpaesiorobici.edu.it/home/wp-content/themes/pasw2015/github/vendor/Parsedown.php on line 894

Il sito sta avendo problemi tecnici. Controlla la casella di posta dell'amministratore del sito per istruzioni.

Soluzione? Grazie per l'attenzione

**Comment by maupao** [comment]
Ciao, stai usando la versione 1.8? C'è una versione che funziona con php 7, trovi le indicazioni qui: http://www.scuolacooperativa.net/wp3-social/versione-pasw2015-per-php7/
